### ISSUE TITLE
dns wont get used

### ISSUE THREAD

**Issue by nilshinsch** [multififa/Subseller_Dns_XtreamCodes1.0.6#2]
hi 
when i set a dns at the reseller and log in to the reseller
it dosnt show the dns that is set when pulling a line

option to disable sub reseller?

**Comment by fmanicone** [comment]
if you wont disable subseller option make your user subseller and they dont show option

i have fix dns now. take new version

**Comment by nilshinsch** [comment]
wo youre fast

working now with the dns
can you make a patch with only dns and no subreseller options?

**Comment by fmanicone** [comment]
You can transform your Reseller in Subseller. Have same capabilities but not have my reseller panel
:-)
